### ISSUE TITLE
MaskContour.find_contour() got an unexpected keyword argument 'image'

### ISSUE THREAD

**Issue by xueqing0622** [ArtBot2023/CharacterFaceSwap#5]
![image](https://github.com/ArtBot2023/CharacterFaceSwap/assets/114840118/eeb5b902-ef73-45ea-b6b6-24b93a729058)

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MaskContour.find_contour() got an unexpected keyword argument 'image'

**Comment by xueqing0622** [comment]
![image](https://github.com/ArtBot2023/CharacterFaceSwap/assets/114840118/acc23a18-ab43-4d73-b486-b26772e7f5d5)
Seem it is drag in workflow mistake, I input this node by myself. Is this one right?

**Comment by xinwolfthorn** [comment]
i have the same exact issue, along with adding the mask contour node myself and coming up with only mask passthrough like op..

**Comment by srdr93** [comment]
same issue here.
